services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
     - POSTGRES_DB=test-gis
     - POSTGRES_USER=west
     - POSTGRES_PASSWORD=password
    ports:
     - 5432:5432
    volumes:
     - ./data/postgis:/var/lib/postgresql/data
