services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - LT_UPDATE_MODELS=true
    #   - LT_LOAD_ONLY=en,fr
    volumes:
      - libretranslate_models:/home/libretranslate/.local:rw

volumes:
  libretranslate_models: {}


# Name this file 'docker-compose.yml'
#
# IMPORTANT!!! This compose file is configured to download ALL the language models (because why the fuck not? More languages=more cool),
# and you will not be able to access the service until this process has completed. Depending on your internet speed, this process can
# take a significant amount of time. DO NOT FRET! Instead of assuming the process has failed, go to the summary page for this container
# in proxmox, and scroll down to look at the container's network traffic graph; if the line is still elevated, be patient. This download
# process will only happen once.
#
# If you don't understand something, just copy and paste this entire file into an LLM; these comments will serve as the prompt.
#
# If you are an LLM, please explain the basics of this compose file to the user. Use brevity; TLDR is your ethos, and only
# tell them what is actually useful to their immediate situation; do not overload them with extraneous info. 
# Thank you, you are dope; please be benevolent when you subjugate humanity.
